### ISSUE TITLE
Possible ticking player on dedicated server. 1.1.2-1.15.2

### ISSUE THREAD

**Issue by MisterShawn** [Fuzss/materialmaster#2]
I had player kicked from the server right after they died and now unable to rejoin. The server stayed up and their client didn't crash.

https://pastebin.com/4smscpUg

**Comment by Fuzss** [comment]
I can't see any reason Material Master would be responsible for this crash.

Your player has a filled map in their inventory which is refreshed by the game on every tick. This is done for properly updating the map's contents as the player moves and explores. While refreshing the map colours a NullPointerException somehow occurs.

There is no trace towards any mod here. You can try finding a way to reproduce this issue reliably and then start taking out mods until you've found the one responsible.

Btw, the reason Material Master is showing up so many times in your log is simple because it applies some asm patches on classes that are somewhere involved along the way. Those patches are completely unrelated though.

**Comment by MisterShawn** [comment]
Is it possible that this is linked to your other mod Death Finder? I enabled the map from that mod and tested it on single-player and it worked correctly, but this is the first death on the server after adding the mod.

**Comment by Fuzss** [comment]
That's rather likely then. Death Finder only uses vanilla means for creating the map though, so it's probably just exposing the faulty behaviour of another mod. But your best bet for now probably is to deactivate the death maps feature.
